---
- name: "Reboot"
  shell: "(sleep 1; reboot) &"
  args:
    executable: /bin/bash
  changed_when: false
  become: true
  async: 100
  poll: 0
  listen: "reboot"
- name: "Wait for host to reboot"
  local_action:
    module: wait_for
    host: "{{ ansible_ssh_host }}"
    port: 22
    delay: 10
    state: started
  listen: "reboot"
